# Generated by Django 4.2.7 on 2024-01-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment_availabledoctors_medworker_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('room', models.IntegerField()),
                ('medical_history', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AvailableDoctors',
        ),
        migrations.RemoveField(
            model_name='procedurejournal',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='procedurejournal',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='procedurejournal',
            name='procedure_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='full_name',
            new_name='fio',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='anamnesis',
            new_name='medical_history',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='room',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='MedWorker',
        ),
        migrations.DeleteModel(
            name='ProcedureJournal',
        ),
    ]
