# Generated by Django 4.2.7 on 2024-01-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctor_medicalstaff_procedurelog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='medicalstaff',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fio',
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='second_name',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='second_name',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='second_name',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
    ]
